name: Download BSB sources
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: ./pull.sh
      - run: |
          git status -s
          if [[ -n "$(git status -s)" ]]; then
            BRANCH="update-$(date '+%Y-%m-%d')"
            COMMIT="Update BSB source file(s)"
            git switch $BRANCH
            git add .
            git config user.name ci
            git config user.email ci@openbible.io
            git commit -m  "$COMMIT"
            git push origin $BRANCH
            gh pr create -B master -H $BRANCH --title "$COMMIT" --body "Created by download.yml"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
