name: Pull audio
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  pull-audio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Setup p7zip fork
        uses: AnimMouse/setup-p7zip-fork@v1
        with:
          version: v17.04 # Need consistent version to diff output archives.
      - run: deno task audio souer
      - name: Zip and release
          run: |
            cd dist
            /opt/7z a -v950m -m0=Copy -sdel souer.zip *
            gh release create -t audio audio-$(date '+%Y-%m-%d') *
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
