name: Pull audio
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force redownload
permissions:
  contents: write

jobs:
  pull-audio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: FedericoCarboni/setup-ffmpeg@v3
      - run: ./build/pull-audio.sh ${{ github.event.inputs.force }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
