name: Pull upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: ./download.sh
      - name: Push and publish
        run: |
          git config user.name ci
          git config user.email ci@openbible.io
          git status -s
          if [[ -n "$(git status -s)" ]]; then
            node build.js
            git add .
            git commit -m 'Download + parse new version'
            VERSION=$(npm version patch)
            git push --tags origin master
            npm whoami
            npm publish --provenance --access public
          fi
