name: Upload
on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno task site
      - name: download release audio
        run: |
            LAST_RELEASE=$(gh release ls --json tagName -q "map(select(.tagName | test(\"^audio-souer-.*\"))) | .[] | .tagName")
            gh release download $LAST_RELEASE
            7z x *.zip -odist
            rm *.z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_UPLOAD }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist
