name: Upload
on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: download release audio
        run: |
            for v in souer gilbert hays; do
              LAST_RELEASE=$(gh release ls --json tagName -q "map(select(.tagName | test(\"^audio-$v-.*\"))) | .[0] | .tagName")
              gh release download $LAST_RELEASE
              7z x *.zip -odist
              rm *.zip
            done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: deno task site
      - run: du -sh dist
      - run: npx wrangler pages deploy dist
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_UPLOAD }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
